/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-02-22 16:27:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import wea5.shop.warehouse.ArticleData;
import java.util.*;

public final class allArticles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1542097924397L));
    _jspx_dependants.put("jar:file:/C:/Public/WEA5/wc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Ue1_BookShop/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064326620000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("wea5.shop.warehouse.ArticleData");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction getXMLHttpRequest() {\r\n");
      out.write("\t\tvar http_request;\r\n");
      out.write("\t\tif (window.XMLHttpRequest) { // Mozilla, Safari, ...\r\n");
      out.write("\t    \thttp_request = new XMLHttpRequest();\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\telse if (window.ActiveXObject) { // IE\r\n");
      out.write("\t\t    try {\r\n");
      out.write("\t\t        http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t    } catch (e) {\r\n");
      out.write("\t\t        try {\r\n");
      out.write("\t\t            http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t        } catch (e) {}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn http_request;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction doRequestArticle(id) {\r\n");
      out.write("\t\thttp_request = getXMLHttpRequest();\r\n");
      out.write("\t\thttp_request.onreadystatechange = displayArticleDetail;\r\n");
      out.write("\t\thttp_request.open('GET', '/");
      out.print(application.getServletContextName() );
      out.write("/BookShopXML?id='+id, true);\r\n");
      out.write("\t\thttp_request.send(null);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction displayArticleDetail() {\r\n");
      out.write("\t\tvar disp = document.getElementById('articledetail');\r\n");
      out.write("        if (http_request.readyState == 4) {\r\n");
      out.write("            if (http_request.status == 200) {\r\n");
      out.write("            \tvar xmldoc = http_request.responseXML;\r\n");
      out.write("\r\n");
      out.write("            \tif (xmldoc.getElementsByTagName('title').item(0) == null) \r\n");
      out.write("            \t\talert('Fehler: der Artikel wurde nicht gefunden!');\r\n");
      out.write("\r\n");
      out.write("            \tvar title = xmldoc.getElementsByTagName(\"title\")[0].childNodes[0].nodeValue;\r\n");
      out.write("            \tvar author = xmldoc.getElementsByTagName(\"author\")[0].childNodes[0].nodeValue;\r\n");
      out.write("            \tvar year = xmldoc.getElementsByTagName(\"year\")[0].childNodes[0].nodeValue;\r\n");
      out.write("            \tvar publisher = xmldoc.getElementsByTagName(\"publisher\")[0].childNodes[0].nodeValue;\r\n");
      out.write("            \t\t\r\n");
      out.write("            \tdisp.innerHTML =  '<h1>' + title + '</h1>';\r\n");
      out.write("            \tdisp.innerHTML += '<p>' + author + '; ' + publisher + '(' + year + ')</p>';  \r\n");
      out.write("            } else {\r\n");
      out.write("                alert('Bei dem Request ist ein Problem aufgetreten.');\r\n");
      out.write("            }\r\n");
      out.write("        }\t\r\n");
      out.write("\t}\r\n");
      out.write("//\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<h3>Article Overview</h3>\r\n");
      out.write("\r\n");
      out.write("<table BGCOLOR=\"#C6EFF7\" cellpadding=\"1\">\r\n");
      out.write("<tr><th>Title</th><th>Price</th><th>buy</th></tr>\r\n");

Collection<ArticleData> articles  = (Collection<ArticleData>) request.getAttribute("articles");
for (Iterator it=articles.iterator(); it.hasNext();) { 
	ArticleData article = (ArticleData) it.next(); 
	
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td>");
      out.print( article.getTitle() );
      out.write("</td>\r\n");
      out.write("         <td>");
      out.print(article.getPrice() );
      out.write("</td>\r\n");
      out.write("         <td><a href=\"/");
      out.print(application.getServletContextName() );
      out.write("/BookShop?cmd=Addtocart&articleid=");
      out.print(article.getId() );
      out.write("\">buy</a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\t");
 
} 

      out.write(" \r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- -- WITH AJAX -- -->\r\n");
      out.write("\r\n");
      out.write("<h3>Article Overview</h3>\r\n");
      out.write("<table BGCOLOR=\"#C6DFF7\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>Title</th>\r\n");
      out.write("\t\t<th>Price</th>\r\n");
      out.write("\t\t<th>Buy</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr noshade=\"noshade\"/>\r\n");
      out.write("<div id=\"articledetail\"></div>\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/allArticles.jsp(86,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/jsp/allArticles.jsp(86,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${articles}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<tr>\r\n");
            out.write("\t\t\t<td><a href=\"javascript:doRequestArticle(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t<td><a href=\"BookShop?cmd=Addtocart&articleid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">buy</a></td>\r\n");
            out.write("\t\t</tr>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
